# Generated by Django 5.1.7 on 2025-03-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vistas', models.IntegerField()),
            ],
        ),
    ]
