# Generated by Django 5.1.7 on 2025-03-15 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='anio',
            new_name='fecha',
        ),
    ]
