# Generated by Django 5.2.3 on 2025-06-28 18:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_remove_pelicula_vistas_alter_pelicula_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))]),
        ),
    ]
