# Generated by Django 5.2.3 on 2025-06-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_alter_pelicula_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
