# Generated by Django 5.2.1 on 2025-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_rename_anio_pelicula_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='vistas',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=100),
        ),
    ]
